### ISSUE TITLE
werkzeug abort is no longer exist.

### ISSUE THREAD

**Issue by MrDataPsycho** [PacktPublishing/Flask-Framework-Cookbook-Second-Edition#1]
Any one follow that book and can not import `from werkzeug import abort` with the newest version of flask use `from werkzeug.exceptions import abort`

**Comment by shalabhaggarwal** [comment]
It still works.
`from werkzeug import abort` works fine as of the latest development build which corresponds to master branch of werkzeug on github for the commit - https://github.com/pallets/werkzeug/commit/c3322bd51fb511fa4be6f208ad048f87d57694d7.
