### ISSUE TITLE
request.is_xhr error

### ISSUE THREAD

**Issue by kravz2702-byte** [PacktPublishing/Flask-Framework-Cookbook-Second-Edition#3]
I have error running app in Chapter_4. Chapter_4/my_app/catalog/views.py in line: "if request.is_xhr or not template". As I understood request module has no is_xhr attribute, but, unfortunately I don't know how to resolve this problem.

**Comment by shalabhaggarwal** [comment]
@kravz2702-byte You are using a version of werkzeug in which this property is deprecated and removed. You can choose to do either of the below approaches:

- Use an older version of werkzeug, like, `werkzeug==0.16.1`
OR
- Write your own logic to detect whether this request is originated with `XMLHttpRequest` headers.

**Comment by kravz2702-byte** [comment]
@shalabhaggarwal, thank you very much for answer
